---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.Namespacename }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.Namespacename }}
  name: {{ .Values.Deploymentname }}
spec:
  selector:
    matchLabels:
      {{- toYaml .Values.matchLabels| nindent 6 }}
  replicas: 5
  template:
    metadata:
      labels:
        {{- toYaml .Values.labels| nindent 8 }}
    spec:
      serviceAccountName: secret-manager
      volumes:
      - name: store-db-secrets
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: {{ .Values.Secretmanagername }}
      containers:
      - image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"
        imagePullPolicy: {{ .Values.containers.imagePullPolicy }}
        name: {{ .Values.containers.name }}
        ports:
        - containerPort: 80
        env:
          - name: APACHE_DOCUMENT_ROOT
            value: '/var/www/html'
          - name: RDS_HOSTNAME
            valueFrom:
              secretKeyRef:
                name: rds-credential
                key: rds_hostname
          - name: RDS_USERNAME
            valueFrom:
              secretKeyRef:
                name: rds-credential
                key: rds_username
          - name: RDS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: rds-credential
                key: rds_password
          - name: RDS_DB_NAME
            valueFrom:
              secretKeyRef:
                name: rds-credential
                key: rds_dbname
          - name: RDS_PORT
            valueFrom:
              secretKeyRef:
                name: rds-credential
                key: rds_port
        volumeMounts:
        - name: store-db-secrets
          mountPath: "/mnt/db/secrets"
          readOnly: true
