apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ .Values.Namespacename }}
  name: {{ .Values.Ingressname }}
  annotations:
    {{- toYaml .Values.annotations| nindent 4 }}
spec:
  defaultBackend:
    service:
      name: {{ .Values.Servicename }}
      port:
        number: 80
  rules:
    - host: rmitstore.group7.com
      http:
        paths:
          - path: /
            pathType: "Prefix"
            backend:
              service:
                name: {{ .Values.Servicename }}
                port:
                  number: 80