apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  namespace: {{ .Values.Namespacename }}
  name: {{ .Values.Secretmanagername }}
spec:
  provider: aws
  parameters:
    objects: |
        - objectName: "arn:aws:secretsmanager:us-east-1:353801319017:secret:credential_prod-7mKBnd"
          jmesPath:
              - path: RDS_HOSTNAME
                objectAlias: hostname
              - path: RDS_USERNAME
                objectAlias: username
              - path: RDS_PASSWORD
                objectAlias: password
              - path: RDS_DB_NAME
                objectAlias: dbname
              - path: RDS_PORT
                objectAlias: port
  # Create k8s secret. It requires volume mount first in the pod and then sync.
  secretObjects:
    - secretName: rds-credential
      type: Opaque
      data:
        #- objectName: <objectName> or <objectAlias> 
        - objectName: hostname
          key: rds_hostname
        - objectName: username
          key: rds_username
        - objectName: password
          key: rds_password
        - objectName: dbname
          key: rds_dbname
        - objectName: port
          key: rds_port