name: cd-dev

on:
  push:
    branches:
      - 'dev'
    paths-ignore:
      - '**.md'

env:
  # Docker Hub
  REGISTRY: docker.io
  PHP_VERSION: 8
  IMAGE_NAME: ${{ github.repository }}
  CONTAINER_NAME: store-webapp
  APP_PORT: 80
  DOCUMENT_ROOT: /var/www/html

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      commit_tag: ${{ steps.meta.outputs.commit_tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Metadata information for build process
      - name: Prepare metadata
        id: meta
        shell: bash
        run: |
          DOCKER_IMAGE=${{ env.IMAGE_NAME }}
          VERSION=latest
          SHORTREF=${GITHUB_SHA::7}
          # Tag with both latest and latest commit SHA
          TAGS="${DOCKER_IMAGE}:${VERSION},${DOCKER_IMAGE}:${SHORTREF}"
          # Set output parameters.
          echo ::set-output name=tags::${TAGS}
          echo ::set-output name=commit_tag::${SHORTREF}
          echo ::set-output name=docker_image::${DOCKER_IMAGE}

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf

      # Login against a Docker registry
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      # Build and Push image
      - name: Build and Push Docker image to Registry
        id: build-and-push
        uses: docker/build-push-action@v3
        with:
          file: ./bin/php${{ env.PHP_VERSION }}/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Pull and Run new version of image as Docker container via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.WEBAPP_HOST_DEV }}
          username: ${{ secrets.WEBAPP_USERNAME_DEV }}
          key: ${{ secrets.WEBAPP_SSH_KEY_DEV }}
          port: 22 # Default SSH Port
          script: |
            docker login ${{ env.REGISTRY }} -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }}
            docker pull ${{ env.IMAGE_NAME }}:${{ needs.build.outputs.commit_tag }}
            docker stop ${{ env.CONTAINER_NAME }}
            docker rm -f ${{ env.CONTAINER_NAME }}
            docker run \
            -e APACHE_DOCUMENT_ROOT='${{ env.DOCUMENT_ROOT }}' \
            -e RDS_HOSTNAME='${{ secrets.RDS_HOSTNAME_DEV }}' \
            -e RDS_USERNAME='${{ secrets.RDS_USERNAME_DEV }}' \
            -e RDS_PASSWORD='${{ secrets.RDS_PASSWORD_DEV }}' \
            -e RDS_DB_NAME='${{ secrets.RDS_DB_NAME_DEV }}' \
            -e RDS_PORT='${{ secrets.RDS_PORT_DEV }}' \
            -p ${{ env.APP_PORT }}:80 \
            --name ${{ env.CONTAINER_NAME }} -d ${{ env.IMAGE_NAME }}:latest

  ui-test:
    runs-on: ubuntu-latest
    needs: deploy
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Setup Python3
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Setup and Run test
        working-directory: ./test/uitests
        run: |
          chmod +x setup_test.sh
          ./setup_test.sh
          pipenv run python -m pytest
