name: Selenium Test

on:
  push:
    branches: [ "php-configuration" ]
  pull_request:
    branches: [ "php-configuration" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
     
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        
    - name: Installed package list
      run: apt list --installed
    
    - name: Install all necessary packages
      run: pip install requests webdriver-manager selenium
      
    - name: Run the scraping script
      run: python selenium_test.py
        
